blogicum/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('category/<slug:category_slug>/', views.category_posts,
         name='category_posts'),
]

blogicum/blogicum/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('blog/', include('blog.urls')),
    path('pages/', include('pages.urls')),
]

blogicum/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('about/', views.about, name='about'),
    path('rules/', views.rules, name='rules'),
    path('contacts/', views.contacts, name='contacts'),
]

blogicum/blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
from blogicum.settings import MAX_LENGTH_TITLE_FIELDS, MAX_LENGTH_SELF_TITLE

# Пользователь, эту модель описывать не нужно, она встроена в Django
User = get_user_model()


class PublishAbstractModel(models.Model):
    # Абстрактная модель с общими полями публикации
    is_published = models.BooleanField(
        default=True,
        verbose_name='Опубликовано',
        help_text='Снимите галочку, чтобы скрыть публикацию.'
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Добавлено'
    )

    class Meta:
        abstract = True


class Post(PublishAbstractModel):
    # Публикация
    title = models.CharField(
        max_length=MAX_LENGTH_TITLE_FIELDS,
        verbose_name='Заголовок'
    )
    text = models.TextField(
        verbose_name='Текст'
    )
    pub_date = models.DateTimeField(
        auto_now=False,
        verbose_name='Дата и время публикации',
        help_text=(
            'Если установить дату и время в '
            'будущем — можно делать отложенные публикации.'
        )
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор публикации',
        related_name='posts'
    )
    location = models.ForeignKey(
        'Location',
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='Местоположение',
        related_name='posts'
    )
    category = models.ForeignKey(
        'Category',
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='Категория',
        related_name='posts'
    )

    class Meta:
        verbose_name = 'публикация'
        verbose_name_plural = 'Публикации'
        default_related_name = 'posts'
        ordering = ('-pub_date',)

        def __str__(self):
            if len(self.title) > MAX_LENGTH_SELF_TITLE:
                return f"{self.title[:MAX_LENGTH_SELF_TITLE]}"
            return f"{self.title}"


class Category(PublishAbstractModel):
    # Тематическая категория
    title = models.CharField(
        max_length=MAX_LENGTH_TITLE_FIELDS,
        verbose_name='Заголовок'
    )
    description = models.TextField(
        verbose_name='Описание'
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Идентификатор',
        help_text=(
            'Идентификатор страницы для URL; разрешены символы латиницы, '
            'цифры, дефис и подчёркивание.'
        )
    )

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'Категории'
        default_related_name = 'categories'

        def __str__(self):
            if len(self.title) > MAX_LENGTH_SELF_TITLE:
                return f"{self.title[:MAX_LENGTH_SELF_TITLE]}"
            return f"{self.title}"


class Location(PublishAbstractModel):
    # Географическая метка
    name = models.CharField(
        max_length=MAX_LENGTH_TITLE_FIELDS,
        verbose_name='Название места'
    )

    class Meta:
        verbose_name = 'местоположение'
        verbose_name_plural = 'Местоположения'
        default_related_name = 'locations'

        def __str__(self):
            if len(self.title) > MAX_LENGTH_SELF_TITLE:
                return f"{self.title[:MAX_LENGTH_SELF_TITLE]}"
            return f"{self.title}"

blogicum/pages/models.py
# from django.db import models

# Create your models here.

blogicum/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from blog.models import Post
from django.utils import timezone
from blogicum.settings import POSTS_RELEASE_LIMIT

# Create your views here.


def get_select_related(limit=None, category_slug=None):
    select_related_variable = Post.objects.select_related(
        'category',
        'location',
        'author'
    ).filter(
        pub_date__lte=timezone.now(),
        is_published=True,
        category__is_published=True
    )
    if limit is None:
        return select_related_variable.filter(category__slug=category_slug)
    return select_related_variable[:limit]


def index(request):
    context = {'posts': get_select_related(limit=POSTS_RELEASE_LIMIT)}
    return render(request, 'blog/index.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(
        Post,
        id=post_id,
        is_published=True,
        pub_date__lte=timezone.now(),
        category__is_published=True,
    )
    context = {'post': post}
    return render(request, 'blog/detail.html', context)


def category_posts(request, category_slug):
    posts = get_select_related(category_slug=category_slug)
    if not posts.exists():
        raise Http404("Категория не найдена")
    selected_context = {
        'category': category_slug,
        'posts': posts
    }
    return render(request, 'blog/category.html', selected_context)

blogicum/pages/views.py
from django.shortcuts import render

# Create your views here.


def about(request):
    template = 'pages/about.html'
    return render(request, template)


def rules(request):
    template = 'pages/rules.html'
    return render(request, template)


def contacts(request):
    template = 'contacts/contacts.html'
    return render(request, template)

blogicum/templates/base.html
{% load static %}
<!DOCTYPE html> 
<html lang="ru"> 

  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image"> 
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'img/fav/android-crome-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="256x256" href="{% static 'img/fav/android-crome-256x256.png' %}">
    
    <!-- Закомментировал эту строку - изначально была она
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    Добавил строку кода из новой версии
    -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">


    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/additional_design.css' %}">
    <title>
      {% block title %}
      {% endblock %}
    </title>
  </head>

  <body>	   
    {% include "includes/header.html"%}
    <main>
      <div class="container py-5">
        {% block content %}
        {% endblock %}          
      </div>
    </main>
    {% include "includes/footer.html" %}
  </body>

</html>

blogicum/templates/blog/category.html
{% extends "base.html" %}

{% block title %}
  Публикации в категории «{{ category.title }}»
{% endblock %}

{% block content %}
  <h1 class="frame_width">Публикации в категории «{{ category.title }}»</h1>
  <p class="mb-5">{{ category.description }}</p>
  {% for post in posts %}
    <article class="mb-5 additional_design frame_width gradient_posts">  
      {% include "includes/post_card.html" %}
    </article>   
  {% endfor %}

{% endblock %}

blogicum/templates/blog/detail.html
{% extends "base.html" %}

{% block title %}
{{ post.title }} | {% if post.location and post.location.is_published %}{{ post.location.name }} |{% endif %} {{ post.pub_date|date:"d E Y" }}
{% endblock %}

{% block content %}
  <article class="additional_design frame_width gradient_posts">
    <p>{{ post.pub_date|date:"d E Y" }} | {% if post.location and post.location.is_published %}{{ post.location.name }}{% else %}Планета Земля{% endif %}<br>
      <small>От автора @{{ post.author.username }} в категории {% include "includes/category_link.html" %}</small></p>
    <h3>{{ post.title }}</h3>
    <p>{{ post.text|linebreaksbr }}</p>
  </article> 
{% endblock %}

blogicum/templates/blog/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Лента записей
{% endblock %}

{% block content %}
  <h1 class="frame_width">Лента записей</h1>                        
  <!-- Перебираем в цикле все посты -->
  {% for post in posts %}
    <hr>
    <article class="additional_design frame_width gradient_posts">
      {% include "includes/post_card.html" %}
    </article>  
  {% endfor %}

{% endblock %}

blogicum/templates/contacts/contacts.html
{% extends "base.html" %}
{% load static %}


{% block title %}
  Контакты
{% endblock %}

{% block content %}

    <h4 class="frame_width">
      Информация про учебному проекту  
    </h4>

    <article class="additional_design frame_width gradient_about">
    <img src="{% static 'img/practicum_logo.png' %}" width="130" height="130" alt="Фото студента" align="left" 
        style="float: left; margin-right: 40px; border-radius: 40%;">
    
    <ul>
      <li>
        Платформа обучения: Яндекс.Практикум          
      </li>
      <li>
        Направление обучения (факультет, специализация): Бэкенд-разработчик
      </li>
      <li>
        Период обучения : май 2025 - март 2026 гг.
      </li>
      <li>
        Учебный проект: Блогикум (спринт 6/20)
      </li>
      <li>
        Stack: Python, Django, Git
      </li>
    </ul>  
    </article>  
    <br>


    <hr>

    
    <br>
    <h4 class="frame_width">
      Виталий В.  
    </h4>

    <article class="additional_design frame_width gradient_about">
    <img src="{% static 'img/avatar.jpg' %}" width="130" height="130" alt="Фото студента" align="left" 
          style="float: left; margin-right: 40px; border-radius: 40%;">
    
    <ul>
      <li>
        E-mail: login@e_mail.ru
      </li>
      <li>
        Phone-number (+WhatsApp, +Telegram): +7 012 345 67 89
      </li>
      <li>
        Соцсети: @link, #link, ...
      </li>
      <li>
        Адрес: Страна, Город, Улица, ...
      </li>
      <li>
        Учебный проект: Блогикум (спринт 6/20)
      </li>
    </ul>               
    </article>                
{% endblock %}

<!-- Тут я хардкодил, не стал больше заморачиваться -->
<!-- class="additional_desain" -->

blogicum/templates/includes/category_link.html
<a class="text-muted" href="{% url 'blog:category_posts' post.category.slug %}">
  «{{ post.category.title }}»
</a>

blogicum/templates/includes/footer.html
{% with request.resolver_match.view_name as view_name %}

<footer class="border-top text-center py-3">
    <p>© Блогикум. 
        {% if view_name == 'pages:about' %}Август, 2025</p>{% endif %}
    {% if view_name == 'pages:about' %}
    <br>
    <p>
        Сайт подготовил<br>
        студент 116 кагорты Яндекс.Практикума<br>
        Виталий В.<br>
        <a href="{% url 'pages:contacts' %}">Связаться</a>
    </p> 
    <br>
    {% endif %}
</footer>
{% endwith %}

blogicum/templates/includes/header.html
{%load static %}
{% with request.resolver_match.view_name as view_name %}

<header class="header_design">
  <nav class="navbar navbar-light" 
  style="
  background: linear-gradient(45deg, #2b09ec70, #d4e47794);
  background-size: 400% 400%;
  animation: gradient-change 7s ease infinite;
  border-radius: 25px
  ">
    <div class="container">
      <a class="navbar-brand" href="{% url 'blog:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        Блогикум
      </a>        
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'blog:index' %}active{% endif %}" href="{% url 'blog:index' %}">
            Лента записей
          </a>
        </li>
        <li class="nav-item">              
          <a class="nav-link {% if view_name == 'pages:about' %}active{% endif %}" href="{% url 'pages:about' %}">
            О проекте
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'pages:rules' %}active{% endif %}" href="{% url 'pages:rules' %}">
            Наши правила
          </a>
        </li>
      </ul>      
    </div>
  </nav> 
</header>
<br>
<br>


{% endwith %}

{% comment %}
<!--
Исходный стиль (оставлил его тут)
style="background-color: lightskyblue"
-->
{% endcomment %}

blogicum/templates/includes/post_card.html
<div>
  <div class="card-body">
    <h5 class="card-title">{{ post.title }}</h5>
    <h6 class="card-subtitle mb-2 text-muted">
      <small>
        {{ post.pub_date|date:"d E Y" }} | {% if post.location and post.location.is_published %}{{ post.location.name }}{% else %}Планета Земля{% endif %}<br>
        От автора @{{ post.author.username }} в категории {% include "includes/category_link.html" %}
      </small>
    </h6>
    <p class="card-text">{{ post.text|linebreaksbr|truncatewords:10 }}</p>
    <a href="{% url 'blog:post_detail' post.id %}" class="card-link">Читать полный текст</a>
  </div>
</div>

blogicum/templates/pages/about.html
{% extends "base.html" %}

{% block title %}
  О проекте
{% endblock %}

{% block content %}
  <h1 class="frame_width">О проекте</h1>
  <article class="additional_design frame_width gradient_about">
  <p>
    Блогикум — это дом для творческих людей. Это — сообщество людей, для которых 
    нет грани между ведением блога и дружбой в социальных сетях. 
  </p>
  <p>
    Дружба и рассказы о новых, неизведанных впечатлениях — вот 
    что вы найдете на нашем ресурсе.  Миллионы блогов по различным темам. 
    Путешествия, политики, развлечения, мода, мода, литература, дизайн и все 
    другие сферы человеческой деятельности. 
  </p>
  <p>
    Творчество, разнообразие и свобода взглядов и самовыражения — 
    основные черты наших пользователей.
  </p>     
</article>
{% endblock %}

blogicum/templates/pages/rules.html
{% extends "base.html" %}

{% block title %}
  Наши правила
{% endblock %}

{% block content %}
  <h1 class="frame_width">Наши правила</h1>
  <article class="additional_design frame_width gradient_rules">
  <p>
    <b>Cамовыражение.</b> У наших пользователей должна 
    быть возможность создать что-то своё, выразить себя, 
    свои мысли и чувства.
  </p>
  <p>
    <b>Многообразие.</b> Мы уважаем и приветствуем разные 
    мнения и культуры. Блогикум — это место, объединяющее 
    самых разных людей. Поделитесь своим уникальным взглядом на мир.  
  </p>
  <p>
    <b>Творчество.</b> Не важно, в какой области вы творите, 
    это может быть литература, дизайн, программирование. 
    Наши инструменты помогут вам раскрыть талант максимально 
    просто и комфортно.   
  </p>
  <p>
    <b>Личность.</b> Мы сохраним ваши сокровенные мысли в тайне. 
    Делитесь своей информацией только с теми, кого выбрали. 
    Как и насколько засекречивать вашу личную информацию — 
    определяете вы и только вы.  
  </p>
</article>
{% endblock %}